### ISSUE TITLE
컴포즈 마이그레이션

### ISSUE THREAD

**Issue by minuxx** [minuxx/nous-android#42]
##  Description
뷰 시스템에서 컴포즈 UI 로 마이그레이션

## Todo
- [ ] 업무 일지 상세 화면
- [ ] 업무 일지 작성 화면
- [ ] 업무 일지 목록 화면
- [ ] 채용뉴스 화면
- [ ] 설정 화면
- [ ] 메인 화면
